### ISSUE TITLE
vs_2022_cpp_build_tools@17.0: hash check failed

### ISSUE THREAD

**Issue by tupini07** [neatorobito/scoop-crystal#12]
It seems that the expected hash for `vs_2022_cpp_build_tools` does not match the actual upstream one. Maybe the upstream installer was updated?

btw, thank you for making this scoop bucket!

**Comment by neatorobito** [comment]
Thanks for catching that. It seems to change more frequently than I expected. I just went ahead and manually updated it for now. I'm gonna leave this issue open while I work on a more permanent solution.

Np, thanks for using it!

**Comment by neatorobito** [comment]
This is resolved by the PR, we'll now automatically check the vsBuildTools executable for a new hash at the same time we check for new crystal nightly binaries.
