### ISSUE TITLE
Recommend `shards` when installing `crystal`

### ISSUE THREAD

**Issue by straight-shoota** [neatorobito/scoop-crystal#14]
I think it's good to have separate packages for `crystal` and `shards`. But it can be confusing when you install `crystal` but don't get `shards` and no information about it. This has already been noticed here: https://forum.crystal-lang.org/t/cant-run-shards-command-on-windows-crystal-v-1-3-0/4243

Most packages ship `shards` with `crystal`, but I think separation is better.
However, it would help to recommend installing `shards` when you install `crystal` (and vice versa probably?).
It seems `scoop` has a `"suggest"` property for this. That would print a recommendation to install `shards` when you install `crystal` (and don't have `shards` installed).

Alternatively, it could also be considered as a dependency. This would install `shards` automatically if you install `crystal`. But that would be wrong. `shards` is only a weak dependency. You can use Crystal perfectly well without `shards`.

**Comment by neatorobito** [comment]
I agree with your points about separation. I added `suggest` to the crystal package manager and then updated the README to include both `crystal` and `shards` in the command for a better experience for novice users. See the screenshot in the linked PR.
