### ISSUE TITLE
Error when run `scoop install vs_2022_cpp_build_tools` after installed it already use vs_BuildTools

### ISSUE THREAD

**Issue by zw963** [neatorobito/scoop-crystal#27]
Please check following screenshot. （选项=option, 未知=unknown)

![image](https://user-images.githubusercontent.com/549126/214907567-e26710ba-8b7b-4a89-a731-a2c453a759f4.png)

I guess the ``--passive`` was passed with without `--` prefix.

Thanks

```
PS C:\Users\zw963> scoop install vs_2022_cpp_build_tools
Installing 'vs_2022_cpp_build_tools' (17.0) [64bit] from crystal-preview bucket
vs_BuildTools.exe (2.0 MB) [=============================================================================================================================================================================] 100%
Checking hash of vs_BuildTools.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\vs_2022_cpp_build_tools\current => ~\scoop\apps\vs_2022_cpp_build_tools\17.0
```

**Comment by neatorobito** [comment]
Thanks for reporting this. It looks like this is a regression in scoop's argument passing, [see this issue for more info](https://github.com/ScoopInstaller/Scoop/issues/5231).

I've got ahead and pushed a patch to keep everything working in this repo and I'll keep a close eye for whatever changes scoop makes.
