### ISSUE TITLE
Error when updating to 1.9.0

### ISSUE THREAD

**Issue by 18183883296** [neatorobito/scoop-crystal#30]
```
Installing 'crystal' (1.9.0) [64bit] from crystal-preview bucket
Loading crystal-1.9.0-windows-x86_64-msvc-unsupported.exe from cache
Linking A:\Scoop\apps\crystal\current => A:\Scoop\apps\crystal\1.9.0
Creating shim for 'crystal'.
Can't shim 'crystal.exe': File doesn't exist.
```

**Comment by straight-shoota** [comment]
> Loading crystal-1.9.0-windows-x86_64-msvc-unsupported.exe from cache

This is the culprit: `.exe` is the new installer, not the archive. Scoop should pick the `.zip` instead. But apparently it just selects the first entry with "windows" in its name.

https://github.com/neatorobito/scoop-crystal/blob/c4c119c8f40eead5f69dfc5f4db433eb7c783ea0/.github/update_mainline.js#L17

I'm trying to mitigate this bug by switching the order of the release assets, then it should hopefully grap the `.zip` as first matching entry.

**Comment by straight-shoota** [comment]
I pushed a fix, it should be working now.

Sorry for the direct commit to `main` branch. I didn't notice I was pushing to upstream directly 🙈

**Comment by 18183883296** [comment]
The hash also need to update perhaps.

**Comment by straight-shoota** [comment]
Yeah, I thought the action workflow would take care of that, but it doesn't (because I had already manually updated the URL).
