### ISSUE TITLE
Hash checking for downloads is gone

### ISSUE THREAD

**Issue by oprypin** [neatorobito/scoop-crystal#5]
https://github.com/neatorobito/scoop-crystal/commit/f5dccd16af15aeceddf3f592e27e0af197b4acd0#diff-51a72be21a2e29db22429ca095acf9be8b06a5360510cc054955feb5f1b65ecc

Why?

**Comment by neatorobito** [comment]
The hashes coming from the update script don't match the hash scoop computes. I've seen this before so I don't think it's the update script. I opted to remove them so that you can still use the package while I investigate.
